# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.9'

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
