name: Test Build

on: [push, pull_request]

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build HTML
        run: python3 -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: _build
